full_name = input("Enter your full name: ")
print(full_name.upper())
print(full_name.lower())
print(len(full_name))
print(full_name.split())
split_name = full_name.split()
print(split_name[0])
print(split_name[1])
print(f"hello {full_name} welcome to python")